### PR TITLE
thirty bees does not use a framework

### PR DESCRIPTION
**Pull request by firstred**

### CODE REVIEW

**Comment by hbakhtiyor** [comment]
why? is it the fork of prestashop which base on symfony?
http://build.prestashop.com/news/prestashop-1-7-and-symfony/

**Comment by firstred** [comment]
Nope, it's forked from 1.6 which did not include a framework.

**Comment by firstred** [comment]
Thank you very much for the quick change!

**Comment by hbakhtiyor** [comment]
np

**Pull request merged**
