### PR TITLE
Adds Aimeos Laravel

### PR DESCRIPTION
**Pull request by aimeos**
The Laravel package is the most popular Aimeos integration

### CODE REVIEW

**Comment by hbakhtiyor** [comment]
hi, thanks for the pr, but there are already in the list

**Comment by hbakhtiyor** [comment]
hi, thanks for the pr, but there are already in the list

**Comment by aimeos** [comment]
Should I update the old one because you are only referencing the Aimeos core but the Laravel integration has 20x more stars

**Comment by aimeos** [comment]
@hbakhtiyor ping

**Comment by hbakhtiyor** [comment]
since aimeos is framework-agnostic i put the core repo, but feel free to change it

**Pull request closed without merging**
